---
variables:
  new-title: "new post title"

actions:
  - name: get-post
    http:
      valid-status:
        - 200
      timeout: "5s"
      target: jsonplaceholder.typicode.com
      method: GET
      port: 443
      protocol: https
      path: "/posts"
      extractors:
        body-json:
          post-title:
            - 0
            - "title"
          post-id:
            - 0
            - "id"

  - name: log-title
    log:
      message: 'title = {{ index .Variables "post-title" }}'

  - name: patch-post
    http:
      valid-status:
        - 200
      timeout: "5s"
      target: jsonplaceholder.typicode.com
      method: PATCH
      headers:
        content-type: "application/json; charset=UTF-8"
      body: |
        {"title": "{{ index .Variables "new-title"}}"}

      port: 443
      protocol: https
      path: '/posts/{{ index .Variables "post-id"}}'

  - name: delete-post
    http:
      valid-status:
        - 200
      timeout: "5s"
      target: jsonplaceholder.typicode.com
      method: DELETE
      port: 443
      protocol: https
      path: '/posts/{{ index .Variables "post-id"}}'
      extractors:
        body: "delete-body"

  - name: log-delete-body
    log:
      message: 'body = {{ index .Variables "delete-body" }}'
